# docker-compose.yml
version: '3.8'

services:
  # Service 1: FastAPI Application
  app:
    build: .
    container_name: complaint_classifier_app
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./feedback:/app/feedback

  # Service 2: The Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Service 3: The Grafana Dashboard Server
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus