    # .github/workflows/ci.yml

name: Complaint Classifier CI Pipeline

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      # We cache dependencies to speed up future runs
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Quality Gate 1 - Lint and Format Check
      - name: Lint and Format Check
        run: |
          pip install black flake8
          black --check.
          # flake8 .

      # Step 5: Quality Gate 2 - Run Tests with Coverage
      - name: Run Tests with Coverage
        run: |
          pip install pytest pytest-cov
          # Run tests and fail if coverage is below 80%
          pytest --cov=src --cov-fail-under=80

      # Step 6: Quality Gate 3 - Validate Docker Build
      - name: Validate Docker Build
        run: docker build -t complaint-classifier .